### PR TITLE
bus window with doubleclick, load symbol

### PR DESCRIPTION
**Pull request by lthurner**
I adapted the bus window so that it can be used to change bus parameter as well as create new buses. If "Edit Elements" is selected in the radio buttons, a double click on a bus opens the bus window, and parameters can be changed. With OK changes are saved, with cancel, they are discarded. If the radio button is on "Create Bus", a single click anywhere in the canvas opens the window to create a new bus.

Combining pick events with doubleclicks is not that simple, I got it to work now but the solution is a little hacky... maybe there will be a better solution still

Also load symbols are now displayed

### CODE REVIEW

**Comment by Tooblippe** [comment]
Great, Can I please ask some advice. I made a lot of changes on my side today. I moved away from PyQt4. I think it will be best in long run. Easy changes to make. and added some more functions and cleaned up some imports etc...

My question is regarding GIT. You now have the pull request and I have come changes that I want to commit. What should my approach be? I have always just used git to save my code and haven't really worked collaboratively, so there is another learning for me.

In what order should I commit my changes and accept your pull request?

**Comment by lthurner** [comment]
Probably the best way is to push your changes, then github will show you if there are any conflicts for merging this pull request. If there are conflicts, you will have to resolve them manually, but github also has a workflow to support this I think (i never tried it).

The best way to prevent conflicts is to push your changes as often as possible, the smaller the changes between each commit the easier it is to merge.

**Comment by Tooblippe** [comment]
thanks. let me do that. You ok with qt5... i ll update all the code etc.... i just tried on my mac and ubuntu and the dependancies via conda keeps on bringing qt5 et al in, you then have to downgrade etc... so i think its better to take the pain now. Will followyour advise above an resolve issus.

**Comment by lthurner** [comment]
Yes I am OK with qt5

Looks like it is not possible to merge anymore, because you made to many changes. Maybe its easier for me to try to integrate my changes into your version, because I know what I changed. I will do that and make a new pull request

**Comment by Tooblippe** [comment]
yea, sorry about that. If you do not mind! I will wait for you. let me know

**Pull request closed without merging**
